#ifndef DT_COT_ARDUINO_LIBRARY_SECRET_HEADER_FILE
#define DT_COT_ARDUINO_LIBRARY_SECRET_HEADER_FILE


/**
 * NB-IoT Credentials
 */

#define NB_IOT_SERVER_IP      "172.25.102.151"
#define NB_IOT_SERVER_PORT    1883
#define NB_IOT_IMSI           "901405800006627" 
#define NB_IOT_COT_PWD        "MyUsx6tX"


#endif /* DT_COT_ARDUINO_LIBRARY_SECRET_HEADER_FILE */
